# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0.xci
# IP: The module: 'oledSystem_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0.xci
# IP: The module: 'oledSystem_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_rst_ps7_0_100M_0/oledSystem_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
