set_property IOSTANDARD LVCMOS18 [get_ports a1]
set_property IOSTANDARD LVCMOS18 [get_ports b1]
set_property IOSTANDARD LVCMOS18 [get_ports c1]
set_property IOSTANDARD LVCMOS18 [get_ports d1]
set_property IOSTANDARD LVCMOS18 [get_ports e1]
set_property IOSTANDARD LVCMOS18 [get_ports select]
set_property IOSTANDARD LVCMOS33 [get_ports out_1]
set_property IOSTANDARD LVCMOS33 [get_ports out_2]
set_property IOSTANDARD LVCMOS33 [get_ports out_3]
set_property IOSTANDARD LVCMOS18 [get_ports f1]

set_property PACKAGE_PIN M15 [get_ports a1]
set_property PACKAGE_PIN H17 [get_ports b1]
set_property PACKAGE_PIN H18 [get_ports c1]
set_property PACKAGE_PIN H19 [get_ports d1]
set_property PACKAGE_PIN F21 [get_ports e1]
set_property PACKAGE_PIN G22 [get_ports f1]

set_property PACKAGE_PIN F22 [get_ports select]
set_property PACKAGE_PIN U14 [get_ports out_1]
set_property PACKAGE_PIN U19 [get_ports out_2]
set_property PACKAGE_PIN W22 [get_ports out_3]