# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_auto_pc_0/oledSystem_auto_pc_0.xci
# IP: The module: 'oledSystem_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_auto_pc_0/oledSystem_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_auto_pc_0/oledSystem_auto_pc_0.xci
# IP: The module: 'oledSystem_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ee.cooper.edu/user/l/lei.chi/oledControlTest/oledControlTest.srcs/sources_1/bd/oledSystem/ip/oledSystem_auto_pc_0/oledSystem_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oledSystem_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
