set_property PACKAGE_PIN M15 [get_ports {s[0]}]
set_property PACKAGE_PIN H17 [get_ports {s[1]}]
set_property PACKAGE_PIN H18 [get_ports {s[2]}]

set_property PACKAGE_PIN U14 [get_ports {d[0]}]
set_property PACKAGE_PIN U19 [get_ports {d[1]}]
set_property PACKAGE_PIN W22 [get_ports {d[2]}]
set_property PACKAGE_PIN V22 [get_ports {d[3]}]
set_property PACKAGE_PIN U21 [get_ports {d[4]}]
set_property PACKAGE_PIN U22 [get_ports {d[5]}]
set_property PACKAGE_PIN T21 [get_ports {d[6]}]
set_property PACKAGE_PIN T22 [get_ports {d[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {s[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {s[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {s[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[7]}]
